{"name": "test_data[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "new_data = 2\n\n    def test_data(new_data):\n        print(\"测试步骤\")\n>       assert new_data == 3\nE       assert 2 == 3\n\nD:\\Python基础\\test\\scripts\\test_fixture_params.py:8: AssertionError"}, "parameters": [{"name": "new_data", "value": "2"}], "start": 1579074481573, "stop": 1579074481573, "uuid": "04b41d8e-f3c4-4e4a-8a95-2b13f7d0799c", "historyId": "70c9b1e55e3198f772f3c0f14daa97e5", "testCaseId": "dd465c263251d58de65400669ad5358e", "fullName": "scripts.test_fixture_params#test_data", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_fixture_params"}, {"name": "host", "value": "TF-201909261319"}, {"name": "thread", "value": "12284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_fixture_params"}]}